/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t*) 0x40021014; // Gpio 18 bit of AHB
	uint32_t *pGpioModeReg = (uint32_t*) 0x48000400; //27-28 bits
	uint32_t *pGpioOutReg = (uint32_t*) 0x48000414; // 13 bit

	// FIRST WE ENABLE RCC-AHB-BIT 18
	uint32_t clkMask = (1UL << 18);
	uint32_t temp = *pClkCtrlReg;
	*pClkCtrlReg = *pClkCtrlReg | clkMask ;

	uint32_t eraseMask = (1UL << 26) | (1UL << 27);
	*pGpioModeReg&= ~eraseMask;// CLEAR
	*pGpioModeReg|= (1UL << 26);
	*pGpioOutReg|= (1UL << 13);

	while(1);




	for(;;);
}
